### PR TITLE
look for files in /data/, correctly delete files from cache

### PR DESCRIPTION
**Pull request by erizocosmico**

### CODE REVIEW

**Review by ajnavarro — APPROVED** [review]

**Review by juanjux — APPROVED** [review]

**Comment by smola** [comment]
@erizocosmico Is this tested with dependant projects?
* go-git (without Go Modules enabled)
* regression-borges/regression-gitbase
* gitbase

**Comment by erizocosmico** [comment]
In gitbase I already tried and it works.
On go-git, it will require changes (it has API changes, it no longer has Init, so no longer SetUpSuite). Also, there is an usage of `fixtures.DataFolder` that no longer applies because the data is no longer on disk (https://github.com/src-d/go-git/blob/662e2c226e9b8352a90cd1951233fab30a4e5042/plumbing/transport/file/upload_pack_test.go#L38). Other than that, it must work.
AFAIK regression-borges/regression-gitbase do not use go-git-fixtures

**Comment by smola** [comment]
I see, the main change was already merged on https://github.com/src-d/go-git-fixtures/pull/18
So a `v4.0.0` release will be required.

cc @mcuadros

**Comment by erizocosmico** [comment]
Yup, needs v4

**Pull request merged**
